# ---- Development Stage ----
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Host 0.0.0.0 para ser acessível fora do container
CMD ["npm", "run", "dev", "--", "--host"]
